/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const EventType = IDL.Variant({
  'social' : IDL.Null,
  'other' : IDL.Null,
  'ride' : IDL.Null,
  'meeting' : IDL.Null,
  'fundraiser' : IDL.Null,
});
export const MemberRole = IDL.Variant({
  'member' : IDL.Null,
  'tailGunner' : IDL.Null,
  'sergeantAtArms' : IDL.Null,
  'vicePresident' : IDL.Null,
  'enforcer' : IDL.Null,
  'prospect' : IDL.Null,
  'secretary' : IDL.Null,
  'roadCaptain' : IDL.Null,
  'chaplain' : IDL.Null,
  'treasurer' : IDL.Null,
  'president' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'joinDate' : Time,
  'name' : IDL.Text,
  'memberRole' : IDL.Opt(MemberRole),
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'title' : IDL.Text,
  'endTime' : Time,
  'description' : IDL.Text,
  'location' : IDL.Text,
  'eventType' : EventType,
});
export const Member = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : MemberRole,
  'photoUrl' : IDL.Text,
});
export const News = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'postedBy' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEvent' : IDL.Func(
      [IDL.Text, IDL.Text, Time, Time, IDL.Text, EventType],
      [],
      [],
    ),
  'addMember' : IDL.Func(
      [IDL.Text, MemberRole, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMember' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getNewsFeed' : IDL.Func([], [IDL.Vec(News)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postNews' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMember' : IDL.Func(
      [IDL.Text, IDL.Text, MemberRole, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const EventType = IDL.Variant({
    'social' : IDL.Null,
    'other' : IDL.Null,
    'ride' : IDL.Null,
    'meeting' : IDL.Null,
    'fundraiser' : IDL.Null,
  });
  const MemberRole = IDL.Variant({
    'member' : IDL.Null,
    'tailGunner' : IDL.Null,
    'sergeantAtArms' : IDL.Null,
    'vicePresident' : IDL.Null,
    'enforcer' : IDL.Null,
    'prospect' : IDL.Null,
    'secretary' : IDL.Null,
    'roadCaptain' : IDL.Null,
    'chaplain' : IDL.Null,
    'treasurer' : IDL.Null,
    'president' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'joinDate' : Time,
    'name' : IDL.Text,
    'memberRole' : IDL.Opt(MemberRole),
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'title' : IDL.Text,
    'endTime' : Time,
    'description' : IDL.Text,
    'location' : IDL.Text,
    'eventType' : EventType,
  });
  const Member = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : MemberRole,
    'photoUrl' : IDL.Text,
  });
  const News = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'postedBy' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEvent' : IDL.Func(
        [IDL.Text, IDL.Text, Time, Time, IDL.Text, EventType],
        [],
        [],
      ),
    'addMember' : IDL.Func(
        [IDL.Text, MemberRole, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMember' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getNewsFeed' : IDL.Func([], [IDL.Vec(News)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postNews' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMember' : IDL.Func(
        [IDL.Text, IDL.Text, MemberRole, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };