/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'id' : string,
  'startTime' : Time,
  'title' : string,
  'endTime' : Time,
  'description' : string,
  'location' : string,
  'eventType' : EventType,
}
export type EventType = { 'social' : null } |
  { 'other' : null } |
  { 'ride' : null } |
  { 'meeting' : null } |
  { 'fundraiser' : null };
export interface Member { 'name' : string, 'role' : MemberRole }
export type MemberRole = { 'member' : null } |
  { 'vicePresident' : null } |
  { 'secretary' : null } |
  { 'roadCaptain' : null } |
  { 'guest' : null } |
  { 'treasurer' : null } |
  { 'president' : null };
export interface News {
  'id' : string,
  'title' : string,
  'postedBy' : string,
  'content' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'joinDate' : Time,
  'name' : string,
  'memberRole' : [] | [MemberRole],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEvent' : ActorMethod<
    [string, string, Time, Time, string, EventType],
    undefined
  >,
  'addMember' : ActorMethod<[string, MemberRole], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getMembers' : ActorMethod<[], Array<Member>>,
  'getNewsFeed' : ActorMethod<[], Array<News>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postNews' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];